export const ROOT_URL = 'https://cpappala.quickbase.com/db/';
export const PARTS = 'bnvm7qmwk';
export const CRAFT_DEMO_APP_TOKEN = 'b8yxnziba5dmpvctznuw8bdaheyw';
export const MAIN = 'main';
export const API_AUTHENTICATE = 'API_Authenticate';
export const USERNAME ='chaitanyakrishna.vtz018@gmail.com';
export const PASSWORD = 'Chaitanya50$';
export const TICKET_LABEL = 'ticket';
export const ADD_RECORD = 'API_AddRecord';
